version: "3.8"

services:
  app:
    container_name: cayf-app
    image: adalfonso/cayf
    restart: unless-stopped
    ports:
      - 4201:4201
    env_file:
      - .env
    volumes:
      # Map work dir paths to (shared) named volumes
      - public_html:/usr/src/app/dist/client
      - nginx_config:/usr/src/app/nginx
    depends_on:
      - mongo

  mongo:
    container_name: cayf-database
    image: mongo:6.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    restart: unless-stopped
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  nginx:
    container_name: cayf-gateway
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - 4200:4200
    volumes:
      - nginx_config:/etc/nginx/conf.d
      - public_html:/var/www/html:ro

      # TODO: Provide paths to SSL cert and key
      - /path/to/cayf/certs/cayf.crt:/etc/ssl/cayf.crt
      - /path/to/cayf/certs/cayf.key:/etc/ssl/cayf.key
    depends_on:
      - app

volumes:
  mongodb:
  mongodb_config:
  public_html:
  nginx_config:
