version: "3.8"

services:
  app:
    container_name: cayf-app
    image: adalfonso/cayf
    restart: unless-stopped
    ports:
      - 4200:4200
    env_file:
      - .env
    volumes:
      # Map work dir paths to (shared) named volumes
      - public_html:/usr/src/app/dist/client

      # Where prompt and prompt_response content goes
      - /path/to/content/json:/src/app/server/content/content.json

      # Certs for wss
      - /path/to/cayf/certs/cayf.crt:/etc/ssl/cayf.crt
      - /path/to/cayf/certs/cayf.key:/etc/ssl/cayf.key

volumes:
  public_html:
