services:
  app:
    build:
      context: .
    ports:
      # node server port
      - 4200:4200
      # node debug port
      - 9229:9229
      - 24678:24678
    env_file:
      - .env
    volumes:
      # bind project root during development for HMR
      - ./client:/usr/src/app/client
      - ./server:/usr/src/app/server
      - ./common:/usr/src/app/common
    command: pnpm dev
